# Generated by Django 5.0.6 on 2024-05-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('milk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vegetables', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('B.E(UG)', 'B.E(UG)'), ('M.E(PG)', 'M.E(PG)'), ('MCA', 'MCA')], max_length=100)),
                ('branch', models.CharField(choices=[('civil', 'civil'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('EEE', 'EEE')], max_length=100)),
                ('hostel_name', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3')], max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.student')),
            ],
        ),
    ]
